"""Railways and supply nodes - the network the game moves supply along.

Neither file was reachable from anywhere in this app, so a mod that added
states or moved a front had no way to connect them: supply simply didn't
flow, and the only fix was editing the raw files by hand.

Both live in `map/` and are plain whitespace-separated numbers, not the
usual brace script:

    map/railways.txt      <level> <province count> <province ids...>
    map/supply_nodes.txt  1 <province id>

The count in a railway line is redundant with the list that follows it, and
the game trusts the count - a line whose count disagrees with its ids is a
silent corruption, so it is always recomputed on write rather than carried
over from whatever was read.
"""

import os
import shutil

from app import undo
from app.game_paths import find_base_game

RAILWAYS = "railways.txt"
SUPPLY_NODES = "supply_nodes.txt"

#: what the game accepts; level 0 would be a railway that isn't there
MAX_LEVEL = 5


def source_path(mod_root, filename):
    """Where to read from: the mod's own copy when it has one, otherwise
    the base game's. Returns "" when neither exists."""
    for root in (mod_root, find_base_game()):
        if not root:
            continue
        candidate = os.path.join(root, "map", filename)
        if os.path.isfile(candidate):
            return candidate
    return ""


def target_path(mod_root, filename):
    """Where edits go - always inside the mod, never the installation."""
    return os.path.join(mod_root, "map", filename)


# ---- reading ----

def parse_railways(path):
    """[(level, [province ids])] in file order.

    Malformed lines are skipped rather than raising: these files are often
    generated by other tools, and one bad line shouldn't cost the user the
    other 899.
    """
    out = []
    try:
        with open(path, "r", encoding="utf-8-sig", errors="ignore") as handle:
            lines = handle.readlines()
    except OSError:
        return out

    for line in lines:
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 3:
            continue
        try:
            level = int(parts[0])
            provinces = [int(p) for p in parts[2:]]
        except ValueError:
            continue
        if len(provinces) < 2:
            continue
        out.append((level, provinces))
    return out


def parse_supply_nodes(path):
    """[province id] for every supply node, in file order."""
    out = []
    try:
        with open(path, "r", encoding="utf-8-sig", errors="ignore") as handle:
            lines = handle.readlines()
    except OSError:
        return out

    for line in lines:
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        try:
            # the leading 1 is a fixed marker; the province is what matters
            out.append(int(parts[-1]))
        except ValueError:
            continue
    return out


# ---- writing ----

def _write(path, text, description):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.isfile(path):
        backup = path + ".bak"
        if not os.path.exists(backup):
            shutil.copy2(path, backup)
    undo.record(path, description)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def format_railways(entries):
    return "".join(
        f"{level} {len(provinces)} " + " ".join(str(p) for p in provinces) + " \n"
        for level, provinces in entries)


def format_supply_nodes(province_ids):
    return "".join(f"1 {province} \n" for province in province_ids)


def save_railways(mod_root, entries):
    path = target_path(mod_root, RAILWAYS)
    _write(path, format_railways(entries), "railways.txt")
    return path


def save_supply_nodes(mod_root, province_ids):
    path = target_path(mod_root, SUPPLY_NODES)
    _write(path, format_supply_nodes(province_ids), "supply_nodes.txt")
    return path


# ---- checks ----

def problems(entries, supply_nodes, land_provinces=None):
    """Things the game will quietly mishandle, as [(index, message)].

    `index` is the railway's position in `entries`, or None for a problem
    with the supply nodes as a whole.
    """
    found = []
    for i, (level, provinces) in enumerate(entries):
        if not 1 <= level <= MAX_LEVEL:
            found.append((i, f"level {level} is outside 1-{MAX_LEVEL}"))
        if len(set(provinces)) != len(provinces):
            found.append((i, "the same province appears twice in one line"))
        if land_provinces is not None:
            strays = [p for p in provinces if p not in land_provinces]
            if strays:
                found.append((i, "not land provinces: "
                                 + ", ".join(str(p) for p in strays[:4])))

    duplicates = {p for p in supply_nodes if supply_nodes.count(p) > 1}
    if duplicates:
        found.append((None, "duplicate supply nodes: "
                            + ", ".join(str(p) for p in sorted(duplicates)[:6])))
    if land_provinces is not None:
        strays = [p for p in supply_nodes if p not in land_provinces]
        if strays:
            found.append((None, "supply nodes on non-land provinces: "
                                + ", ".join(str(p) for p in strays[:6])))
    return found
